POST http://35.172.163.23:8000/login
Content-Type: application/json

{
    "username": "gmodi",
    "password": "brisingr"
}

###

POST http://localhost:8009/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@test.com",
    "password": "brisingr"
}

###

POST http://localhost:8009/getLists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

###

POST http://localhost:8009/getTasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

{
    "note_id": 1
}

###

POST http://localhost:8000/createList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzIyOTM4Mjc0LCJleHAiOjE3MjI5NDU0NzR9.p_rYEbl9YrkiYRIJllHkvoc9dRmGWVAdEZXauStRZrU
Content-Type: application/json

{
    "title": "Test List69",
    "tasks": ["Create a createList function", "Test the function", "???", "Profit"]
}

###

POST http://localhost:8000/updateList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzIyOTM4Mjc0LCJleHAiOjE3MjI5NDU0NzR9.p_rYEbl9YrkiYRIJllHkvoc9dRmGWVAdEZXauStRZrU
Content-Type: application/json

{
    "note_id": "Test List69",
    "list": ["Create a createList function", "Test the function", "???", "Profit"]
}


###

POST http://localhost:8009/updateTitle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

{
    "list_id": 1,
    "title": "My first List, again"
}

###

POST http://localhost:8009/createNote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

{
    "title": "Test Noteasdfnsajkdfnasnjkfnasdf",
    "message": "This is a test message"
}

###

POST http://localhost:8009/getMessage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

{
    "note_id": 22
}

###

DELETE  http://localhost:8009/deleteNote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MywiaWF0IjoxNzEzNTIxNjc2LCJleHAiOjE3MTM1Mjg4NzZ9.IVAgWfWkzEUFzmW3W3ivookRs8BD9yTVX6rCgkyD8Fw
Content-Type: application/json

{
    "note_id": 11
}

###


